import { Injectable, Logger, HttpException, HttpStatus } from '@nestjs/common';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, Not, IsNull, In } from 'typeorm';
import { Milestone } from '../../entities/milestone.entity';
import { WorkflowInstance } from '../../entities/workflow-instance.entity';
import { INVOICE_EVENTS } from '../../events/event-constants';
import { InvoiceCreatedEvent, InvoicePaidEvent } from '../../events/workflow.events';

/**
 * Invoice Integration Service
 * 
 * Handles all integration with Module 01 (Invoice Management)
 * - Auto-generates invoices upon milestone completion
 * - Links invoices to milestones
 * - Listens to invoice events
 */
@Injectable()
export class InvoiceIntegrationService {
    private readonly logger = new Logger(InvoiceIntegrationService.name);
    private readonly module01BaseUrl: string;

    constructor(
        private readonly eventEmitter: EventEmitter2,
        private readonly httpService: HttpService,
        @InjectRepository(Milestone)
        private readonly milestoneRepository: Repository<Milestone>,
        @InjectRepository(WorkflowInstance)
        private readonly workflowInstanceRepository: Repository<WorkflowInstance>,
    ) {
        this.module01BaseUrl = process.env.MODULE_01_URL || 'http://localhost:3001';
        this.logger.log(`Invoice Integration initialized - Module 01 URL: ${this.module01BaseUrl}`);
    }

    /**
     * Create invoice for completed milestone
     */
    async createMilestoneInvoice(milestoneId: string): Promise<{
        invoiceId: string;
        invoiceNumber: string;
        amount: number;
    }> {
        try {
            this.logger.log(`Creating invoice for milestone: ${milestoneId}`);

            // Fetch milestone with workflow details
            const milestone = await this.milestoneRepository.findOne({
                where: { id: milestoneId, isDeleted: false },
                relations: ['workflowInstance', 'workflowInstance.workflowDefinition'],
            });

            if (!milestone) {
                throw new HttpException(
                    `Milestone ${milestoneId} not found`,
                    HttpStatus.NOT_FOUND,
                );
            }

            if (milestone.invoiceId) {
                this.logger.warn(`Milestone ${milestoneId} already has invoice: ${milestone.invoiceId}`);
                return {
                    invoiceId: milestone.invoiceId,
                    invoiceNumber: milestone.invoiceNumber,
                    amount: milestone.paymentAmount,
                };
            }

            // Prepare invoice data
            const invoiceData = {
                tenantId: milestone.tenantId,
                customerId: milestone.customerId || milestone.workflowInstance?.customerId,
                amount: milestone.paymentAmount,
                currency: milestone.currency || 'INR',
                dueDate: milestone.dueDate || this.calculateDueDate(milestone.completedAt),
                description: this.generateInvoiceDescription(milestone),
                lineItems: [
                    {
                        description: `Milestone: ${milestone.name}`,
                        quantity: 1,
                        unitPrice: milestone.paymentAmount,
                        total: milestone.paymentAmount,
                    },
                ],
                metadata: {
                    milestoneId: milestone.id,
                    workflowInstanceId: milestone.workflowInstanceId,
                    workflowDefinitionId: milestone.workflowInstance?.workflowDefinitionId,
                    autoGenerated: true,
                    source: 'Module_05_Milestone',
                },
                tags: ['milestone-payment', `workflow-${milestone.workflowInstanceId}`],
            };

            // Call Module 01 API to create invoice
            const response = await firstValueFrom(
                this.httpService.post(
                    `${this.module01BaseUrl}/api/v1/invoices`,
                    invoiceData,
                    {
                        headers: {
                            'Content-Type': 'application/json',
                            'X-Tenant-ID': milestone.tenantId,
                        },
                        timeout: 10000,
                    }
                )
            );

            const invoice = response.data.data || response.data;

            // Update milestone with invoice reference
            await this.milestoneRepository.update(milestoneId, {
                invoiceId: invoice.id,
                invoiceNumber: invoice.invoiceNumber,
                invoiceGeneratedAt: new Date(),
                updatedAt: new Date(),
            });

            this.logger.log(
                `Invoice created successfully - Invoice ID: ${invoice.id}, Milestone ID: ${milestoneId}`
            );

            return {
                invoiceId: invoice.id,
                invoiceNumber: invoice.invoiceNumber,
                amount: invoice.amount,
            };
        } catch (error) {
            this.logger.error(
                `Failed to create invoice for milestone ${milestoneId}: ${error.message}`,
                error.stack,
            );

            // Log failure but don't block milestone completion
            await this.milestoneRepository.update(milestoneId, {
                invoiceGenerationError: error.message,
                updatedAt: new Date(),
            });

            throw new HttpException(
                `Invoice generation failed: ${error.message}`,
                error.response?.status || HttpStatus.INTERNAL_SERVER_ERROR,
            );
        }
    }

    /**
     * Link existing invoice to milestone
     */
    async linkInvoiceToMilestone(milestoneId: string, invoiceId: string, invoiceNumber: string): Promise<void> {
        try {
            await this.milestoneRepository.update(milestoneId, {
                invoiceId,
                invoiceNumber,
                invoiceGeneratedAt: new Date(),
                updatedAt: new Date(),
            });

            this.logger.log(`Invoice ${invoiceId} linked to milestone ${milestoneId}`);
        } catch (error) {
            this.logger.error(`Failed to link invoice to milestone: ${error.message}`);
            throw error;
        }
    }

    /**
     * Handle invoice created event from Module 01
     */
    async handleInvoiceCreated(event: InvoiceCreatedEvent): Promise<void> {
        try {
            const milestoneId = event.metadata?.milestoneId;

            if (!milestoneId) {
                // Not a milestone-related invoice, ignore
                return;
            }

            this.logger.log(`Received invoice.created event for milestone: ${milestoneId}`);

            await this.linkInvoiceToMilestone(
                milestoneId,
                event.invoiceId,
                event.metadata.invoiceNumber || event.invoiceId,
            );
        } catch (error) {
            this.logger.error(`Error handling invoice.created event: ${error.message}`);
        }
    }

    /**
     * Handle invoice paid event from Module 01
     */
    async handleInvoicePaid(event: InvoicePaidEvent): Promise<void> {
        try {
            const milestoneId = event.metadata?.milestoneId;

            if (!milestoneId) {
                return;
            }

            this.logger.log(`Received invoice.paid event for milestone: ${milestoneId}`);

            // Update milestone status
            const milestone = await this.milestoneRepository.findOne({
                where: { id: milestoneId, isDeleted: false },
            });

            if (milestone) {
                await this.milestoneRepository.update(milestoneId, {
                    paymentStatus: 'PAID',
                    paidAt: event.paidAt,
                    paidAmount: event.paidAmount,
                    updatedAt: new Date(),
                });

                // Emit milestone payment completed event
                this.eventEmitter.emit('milestone.payment.completed', {
                    milestoneId,
                    invoiceId: event.invoiceId,
                    paidAmount: event.paidAmount,
                    paidAt: event.paidAt,
                });

                this.logger.log(`Milestone ${milestoneId} marked as paid`);
            }
        } catch (error) {
            this.logger.error(`Error handling invoice.paid event: ${error.message}`);
        }
    }

    /**
     * Check if milestone can generate invoice
     */
    isEligibleForInvoice(milestone: Milestone): boolean {
        return (
            milestone.status === 'COMPLETED' &&
            milestone.paymentAmount > 0 &&
            !milestone.invoiceId &&
            milestone.autoGenerateInvoice !== false
        );
    }

    /**
     * Generate invoice description from milestone
     */
    private generateInvoiceDescription(milestone: Milestone): string {
        const parts = [
            `Milestone Payment: ${milestone.name}`,
        ];

        if (milestone.description) {
            parts.push(milestone.description);
        }

        if (milestone.workflowInstance) {
            parts.push(`Workflow: ${milestone.workflowInstance.name}`);
        }

        return parts.join(' | ');
    }

    /**
     * Calculate due date for invoice (default: 30 days from completion)
     */
    private calculateDueDate(completedAt: Date | null): Date {
        const baseDate = completedAt || new Date();
        const dueDate = new Date(baseDate);
        dueDate.setDate(dueDate.getDate() + 30); // 30 days net
        return dueDate;
    }

    /**
     * Get invoices for workflow instance
     */
    async getWorkflowInvoices(workflowInstanceId: string): Promise<any[]> {
        try {
            const milestones = await this.milestoneRepository.find({
                where: {
                    workflowInstanceId,
                    invoiceId: Not(IsNull()),
                    isDeleted: false,
                },
            });

            const invoiceIds = milestones.map(m => m.invoiceId).filter(Boolean);

            if (invoiceIds.length === 0) {
                return [];
            }

            // Fetch invoice details from Module 01
            const response = await firstValueFrom(
                this.httpService.get(
                    `${this.module01BaseUrl}/api/v1/invoices`,
                    {
                        params: {
                            ids: invoiceIds.join(','),
                        },
                        timeout: 10000,
                    }
                )
            );

            return response.data.data || response.data || [];
        } catch (error) {
            this.logger.error(`Failed to fetch workflow invoices: ${error.message}`);
            return [];
        }
    }
}
