import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, ManyToOne, JoinColumn } from 'typeorm';
import { RiskIndicator } from './risk-indicator.entity';

/**
 * Entity representing alerts generated by the early warning system.
 * This stores alerts, their status, and related information.
 */
@Entity('risk_alerts')
export class RiskAlert {
  /**
   * Unique identifier for the risk alert
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * Tenant ID for multi-tenancy support
   */
  @Column({ name: 'tenant_id' })
  tenantId: string;

  /**
   * Buyer ID this alert applies to
   */
  @Column({ name: 'buyer_id' })
  buyerId: string;

  /**
   * Alert type (e.g., payment_risk, credit_limit, financial_health)
   */
  @Column({ name: 'alert_type', length: 50 })
  alertType: string;

  /**
   * Alert title
   */
  @Column({ name: 'title', length: 200 })
  title: string;

  /**
   * Alert message
   */
  @Column({ name: 'message', type: 'text' })
  message: string;

  /**
   * Alert severity (e.g., low, medium, high, critical)
   */
  @Column({ name: 'severity', length: 20 })
  severity: string;

  /**
   * Alert priority (1-5, where 1 is highest)
   */
  @Column({ name: 'priority', type: 'integer' })
  priority: number;

  /**
   * Status of this alert (e.g., new, in_progress, resolved, dismissed)
   */
  @Column({ name: 'status', length: 20, default: 'new' })
  status: string;

  /**
   * Risk indicator IDs that triggered this alert
   */
  @Column({ name: 'risk_indicator_ids', type: 'jsonb' })
  riskIndicatorIds: string[];

  /**
   * Recommended actions
   */
  @Column({ name: 'recommended_actions', type: 'text', nullable: true })
  recommendedActions: string;

  /**
   * Due date for action
   */
  @Column({ name: 'due_date', type: 'timestamp', nullable: true })
  dueDate: Date;

  /**
   * Assigned user ID
   */
  @Column({ name: 'assigned_to', nullable: true })
  assignedTo: string;

  /**
   * Assigned user name
   */
  @Column({ name: 'assigned_to_name', length: 100, nullable: true })
  assignedToName: string;

  /**
   * Assignment date
   */
  @Column({ name: 'assigned_at', type: 'timestamp', nullable: true })
  assignedAt: Date;

  /**
   * Resolution date
   */
  @Column({ name: 'resolved_at', type: 'timestamp', nullable: true })
  resolvedAt: Date;

  /**
   * Resolution notes
   */
  @Column({ name: 'resolution_notes', type: 'text', nullable: true })
  resolutionNotes: string;

  /**
   * User ID who resolved this alert
   */
  @Column({ name: 'resolved_by', nullable: true })
  resolvedBy: string;

  /**
   * Whether this alert has been read
   */
  @Column({ name: 'is_read', type: 'boolean', default: false })
  isRead: boolean;

  /**
   * User ID who read this alert
   */
  @Column({ name: 'read_by', nullable: true })
  readBy: string;

  /**
   * Timestamp when this alert was read
   */
  @Column({ name: 'read_at', type: 'timestamp', nullable: true })
  readAt: Date;

  /**
   * Notification channels used for this alert (e.g., email, sms, in_app)
   */
  @Column({ name: 'notification_channels', type: 'jsonb', nullable: true })
  notificationChannels: string[];

  /**
   * Notification status for each channel
   */
  @Column({ name: 'notification_status', type: 'jsonb', nullable: true })
  notificationStatus: Record<string, string>;

  /**
   * JSON object containing additional data
   */
  @Column({ name: 'additional_data', type: 'jsonb', nullable: true })
  additionalData: Record<string, any>;

  /**
   * Timestamp when the record was created
   */
  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  /**
   * Timestamp when the record was last updated
   */
  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
