export enum LegalSpecialty {
    CORPORATE_LAW = 'CORPORATE_LAW',
    CONTRACT_LAW = 'CONTRACT_LAW',
    DISPUTE_RESOLUTION = 'DISPUTE_RESOLUTION',
    COMPLIANCE = 'COMPLIANCE',
    INTELLECTUAL_PROPERTY = 'INTELLECTUAL_PROPERTY'
}
